# docker run -it -d -p 11000:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http

FROM codercom/code-server

CMD docker run -it -p 8443:8443 -v "${PWD}:/home/coder/project"  --allow-http